-- ==========================================
-- SUPABASE DATABASE SETUP FOR STAYEASY / STAYEASE
-- Run this script in your Supabase SQL Editor
-- ==========================================

-- 1. Create Hotels Table
CREATE TABLE IF NOT EXISTS public.hotels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    description TEXT,
    rating NUMERIC(3, 1) DEFAULT 4.5,
    price NUMERIC(10, 2) NOT NULL,
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Bookings Table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE SET NULL,
    hotel_name TEXT NOT NULL,
    location TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    user_name TEXT NOT NULL,
    user_email TEXT NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests INTEGER DEFAULT 1,
    status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- 4. Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow public read access to hotels" ON public.hotels;
DROP POLICY IF EXISTS "Allow public select on bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow public insert on bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow public update on bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow public delete on bookings" ON public.bookings;

-- 5. Create Policies for Hotels (Public Read)
CREATE POLICY "Allow public read access to hotels"
ON public.hotels FOR SELECT
USING (true);

-- 6. Create Policies for Bookings (Public Read, Create, Update, Delete)
CREATE POLICY "Allow public select on bookings"
ON public.bookings FOR SELECT
USING (true);

CREATE POLICY "Allow public insert on bookings"
ON public.bookings FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public update on bookings"
ON public.bookings FOR UPDATE
USING (true);

CREATE POLICY "Allow public delete on bookings"
ON public.bookings FOR DELETE
USING (true);

-- 7. Seed Initial Hotels Data
INSERT INTO public.hotels (name, location, description, rating, price, image)
VALUES
  ('Grand Palace Hotel', 'Bengaluru, India', 'A comfortable luxury hotel with modern rooms, fine dining, and pool amenities.', 4.8, 3500, 'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=900&q=80'),
  ('Royal Comfort Inn', 'Mumbai, India', 'Enjoy a relaxing stay close to popular city attractions and business hubs.', 4.6, 2800, 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=900&q=80'),
  ('Lake View Resort', 'Udaipur, India', 'A stylish resort with breathtaking lake views and traditional Indian architecture.', 4.9, 4200, 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=900&q=80'),
  ('Ocean Breeze Resort', 'Goa, India', 'Relax near the serene coast and enjoy a peaceful beachside getaway.', 4.7, 4000, 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=900&q=80')
ON CONFLICT DO NOTHING;
